[tool.poetry]
name = "science_mode_4"
version = "0.1"
description = "Native ScienceMode4 protocol implementation"
authors = ["Marc Hofmann"]
license = "MIT"
readme = "README.md"
include = ["examples/*"]